// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKng1fJYqgZFmoUH3RsQ41uMyhVYL430',
    appId: '1:862938584179:web:386456c03c4c2bda8bc606',
    messagingSenderId: '862938584179',
    projectId: 'finance-7c257',
    authDomain: 'finance-7c257.firebaseapp.com',
    storageBucket: 'finance-7c257.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_F3OEsoVl1tbcyKF_Y_hvWbG4qscc08',
    appId: '1:862938584179:android:faace57327a5f5068bc606',
    messagingSenderId: '862938584179',
    projectId: 'finance-7c257',
    storageBucket: 'finance-7c257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6lOurttWCma9Hy2K4WeGbUpI_2E6hiiI',
    appId: '1:862938584179:ios:913ab7a58757620e8bc606',
    messagingSenderId: '862938584179',
    projectId: 'finance-7c257',
    storageBucket: 'finance-7c257.appspot.com',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6lOurttWCma9Hy2K4WeGbUpI_2E6hiiI',
    appId: '1:862938584179:ios:2d77dc1386c27f6f8bc606',
    messagingSenderId: '862938584179',
    projectId: 'finance-7c257',
    storageBucket: 'finance-7c257.appspot.com',
    iosBundleId: 'com.example.finance.RunnerTests',
  );
}
